# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'meshiiru' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn'
  pod 'GoogleAPIClient/Calendar', '~> 1.0'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Pods for meshiiru

  target 'meshiiruTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
