# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meshiiru' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for meshiiru

  target 'meshiiruTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
